### ISSUE TITLE
代码逻辑上就有问题啊WaitNotify，你确定测试通过了？

### ISSUE THREAD

**Issue by hktalent** [xhyonline/p2p-demo#1]
代码逻辑上就有问题啊WaitNotify，你确定测试通过了？
```
func (s *Handler) WaitNotify() {
	buffer := make([]byte, 1024)
	n, err := s.ServerConn.Read(buffer)
	if err != nil {
		panic("从服务器获取用户地址失败" + err.Error())
	}
```
两个client不可能同时启动吧？即便同时启动
那么这里永远都会退出来哦

如果连接了server，留下一个临时的ip:port，第二次启动还能用吗？

**Comment by xhyonline** [comment]
demo你跑一下就知道了。

demo很简易，目的只是展示让两个nat背后的client直连，没考虑别的。如果有需要可以自行设计，否则怎么叫demo呢？

**Comment by hktalent** [comment]
@xhyonline ok, thanks
